# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MixogyMain' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire', '~> 5.0.0-rc.3'
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5.1.0'
  pod 'BottomPopup', '0.5.4'
  pod 'Cartography'
  pod 'ObjectMapper', '~> 3.4'
  pod 'SVProgressHUD'
  pod 'SDWebImage', '3.8.2'
  pod 'DropDown'
  pod 'ActionSheetPicker-3.0'
  pod 'ImagePicker'
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'IQKeyboardManager'
  pod 'UITextView+Placeholder'
  pod 'Agrume'
  pod 'SKCountryPicker'
  pod 'PBJVideoPlayer'
  pod 'VersaPlayer'
  pod 'Firebase/Auth'
  pod 'CodableFirebase'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'StreamingKit'
  pod 'FirebaseUI/Storage'
  pod 'IQAudioRecorderController'
  pod 'GSImageViewerController'
  pod 'ImageSlideshow', '~> 1.8.3'
  pod 'ImageSlideshow/SDWebImage'
  pod 'MaterialComponents/TextFields'
  pod 'MaterialComponents/TextControls+FilledTextAreas'
  pod 'MaterialComponents/TextControls+FilledTextFields'
  pod 'MaterialComponents/TextControls+OutlinedTextAreas'
  pod 'MaterialComponents/TextControls+OutlinedTextFields'
  pod 'MobilePlayer'
  pod 'EzPopup'
  pod 'Firebase/Messaging'

  target 'MixogyMainTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
